// Generated by tools.sdkgen; DO NOT EDIT.
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Headroom.GeneratedPilot;

[JsonConverter(typeof(OptionalJsonConverterFactory))]
public readonly record struct Optional<T>(bool IsSet, T? Value)
{
    public static Optional<T> FromValue(T? value) => new(true, value);
}

public sealed class OptionalJsonConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Optional<>);
    public override JsonConverter CreateConverter(Type type, JsonSerializerOptions options)
    {
        var valueType = type.GetGenericArguments()[0];
        return (JsonConverter)Activator.CreateInstance(typeof(OptionalJsonConverter<>).MakeGenericType(valueType))!;
    }
    private sealed class OptionalJsonConverter<T> : JsonConverter<Optional<T>>
    {
        public override Optional<T> Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) =>
            Optional<T>.FromValue(JsonSerializer.Deserialize<T>(ref reader, options));
        public override void Write(Utf8JsonWriter writer, Optional<T> value, JsonSerializerOptions options) =>
            JsonSerializer.Serialize(writer, value.Value, options);
    }
}

public sealed class RetrievalError
{
    [JsonPropertyName("detail")]
    public required string Detail { get; init; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement> AdditionalProperties { get; init; } = new();
}

public sealed class RetrieveRequest
{
    [JsonPropertyName("hash")]
    public required string Hash { get; init; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement> AdditionalProperties { get; init; } = new();
}

public sealed class RetrieveResponse
{
    [JsonPropertyName("compressed_item_count")]
    public required long CompressedItemCount { get; init; }

    [JsonPropertyName("hash")]
    public required string Hash { get; init; }

    [JsonPropertyName("original_content")]
    public required string OriginalContent { get; init; }

    [JsonPropertyName("original_item_count")]
    public required long OriginalItemCount { get; init; }

    [JsonPropertyName("original_tokens")]
    public required long OriginalTokens { get; init; }

    [JsonPropertyName("retrieval_count")]
    public required long RetrievalCount { get; init; }

    [JsonPropertyName("tool_name")]
    public required string? ToolName { get; init; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement> AdditionalProperties { get; init; } = new();
}

